name = input("Enter student name: ")
roll = input("Enter roll number: ")
course = input("Enter course: ")
marks = int(input("Enter marks: "))
print("\n--- Student Details ---")
print("Name:", name)
print("Roll Number:", roll)
print("Course:", course)
print("Marks:", marks)